name: Linting

on: [push, pull_request]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint with ruff 
        uses: chartboost/ruff-action@v1
        with:
          src: "."
          version: 0.0.290
